version: '3.5'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongodb:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=xhp
      - ME_CONFIG_BASICAUTH_PASSWORD=xhp
    depends_on:
      - mongodb

  backend:
    build: backend/
    ports:
      - 3001:3001
    image: web-backend
    container_name: web-backend
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://api_user:api1234@mongodb:27017/api_dev_db?authSource=api_dev_db
    depends_on:
      - mongodb
      - mongo-express
  frontend:
    build: frontend/
    ports:
      - 3000:3000
    image:  web-frontend
    container_name: web-frontend
    stdin_open: true
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
    depends_on:
      - backend
    
volumes:
  mongodb: